### ISSUE TITLE
Configure custom `fetch` function

### ISSUE THREAD

**Issue by stefanoverna** [DaBigBlob/libsql-stateless#3]
It would be fantastic if there was the ability to add the option to configure a custom `fetch` function: 

https://github.com/DaBigBlob/libsql-stateless/blob/main/src/types.ts#L5-L8

Next.js essentially makes it mandatory to manually set a `fetch` function to overwrite its awful defaults. 

This would also make the work of libsql-stateless-easy more convenient, as it would not be forced to overwrite the global `fetch`. 

Is there any technical reason why this has not been done so far? 

If you are interested in a potential PR and would be willing to merge it quickly, I would be happy to work on it!

**Comment by DaBigBlob** [comment]
I haven't used next.js in more than a few years but patching fetch seems like an awful awful decision and an insulting disregard for other libraries that use fetch.

> Is there any technical reason why this has not been done so far?

libsql-stateless was meant to be a js/ts driver that strictly adheres to the libsql http api specs while being as fast as possible.
This meant *doing* as less as possible. Using custom fetch is yet another thing to be *done* and at the time didn't seem like an important enough feature.
However its a small tradeoff and seems like kind of a necessity when working with next.js.

The next release should have an option for custom fetch.

**Comment by stefanoverna** [comment]
> I haven't used next.js in more than a few years but patching fetch seems like an awful awful decision and an insulting disregard for other libraries that use fetch.

I cannot agree more. Thank you!

**Comment by DaBigBlob** [comment]
version 2.8.5 for libsql-stateless has been released.
the custom fetch config is now available.

i will soon update libsql-stateless-easy to use this version.

**Comment by DaBigBlob** [comment]
version 1.6.11 published for libsql-stateless-easy.

**Comment by stefanoverna** [comment]
Super fast! Thank you @DaBigBlob!
